name: advanced_terminal
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.3

dependencies:
  meta: ^1.15.0
  ffi: '>=1.0.0 <3.0.0'
  dart_console: ^4.1.2

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
