include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    public_member_api_docs: false # TODO: change to true
    avoid_positional_boolean_parameters: false # TODO: change to true
    library_names: true
    library_prefixes:
      'dart:io': io
      'dart:async': async
      'dart:math': math
      'package:image/image.dart': img
      'package:dart_console/src/ffi/termlib.dart': console

analyzer:
  exclude:
    - packages/**
    - manual_test/local/**
