name: dart_tui
description: A library for creating TUI interfaces in dart
version: 0.0.1
repository: https://github.com/bit-burger/dart-tui

environment:
  sdk: ^3.9.2

dependencies:
  dart_console: ^4.1.2
  flutter:
    sdk: flutter
  image: ^4.5.4

dev_dependencies:
  very_good_analysis: ^5.0.0
  import_sorter: ^4.6.0
  test: ^1.21.0
